### ISSUE TITLE
Notification System Needed

### ISSUE THREAD

**Issue by ChrisChasm** [DiscipleTools/disciple-tools#128]
We're developed a workflow for the notifications system. 
![screen shot 2017-09-18 at 7 15 41 am](https://user-images.githubusercontent.com/7318348/30554572-3c1aa436-9c62-11e7-8ef5-92011a48c2dd.png)

- [x] @mention process https://github.com/ChasmSolutions/disciple-tools/pull/157
- [x] assigned_to event https://github.com/ChasmSolutions/disciple-tools/pull/157
- [x] update needed event https://github.com/ChasmSolutions/disciple-tools/pull/157
- [x] milestone event
- [x] contact details event
- [x] sharing event

**Comment by ChrisChasm** [comment]
#155 
#149 

These are two conversations that tie to this task.

**Comment by ChrisChasm** [comment]
We're developed a workflow for the notifications system. 
![screen shot 2017-09-18 at 7 15 41 am](https://user-images.githubusercontent.com/7318348/30554572-3c1aa436-9c62-11e7-8ef5-92011a48c2dd.png)

- [ ] @mention process
- [ ] assigned_to event
- [ ] update needed event
- [ ] milestone event
- [ ] contact details event
- [ ] sharing event

**Comment by ChrisChasm** [comment]
@ahillbilly @corsacca 
- [ ] If I am @mentioned on a contact that I don't have access to, what do we expect to happen. Right now any link would go to a 404 page. Should I include in the @mention process a share record for that person. This way if you @mention anyone, they will automatically become a share on the contact?

**Comment by corsacca** [comment]
I like that idea. If you are @mentioned you are added to the share record.
What we have to be careful with is that the person @mentioned usually does not want to receive any other notifications about the contact.
We might need to explore having a notifications button to opt in or opt out of notification for a contact.

**Comment by ChrisChasm** [comment]
I just experimented with it, and it works like a charm.

**Comment by ahillbilly** [comment]
This is the functionality of the prototype system and I like the continued direction that an @mention also creates a share.

**Comment by ChrisChasm** [comment]
The core of the notifications system is built and working. I did not add the email features, because we need to build the preferences section first, and then build the email settings with those preferences check.
