### ISSUE TITLE
Thougths about GPLv3

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools#154]
from @burntsun 
About trademarks: the GPLv3 has no implications at all for trademarks, only for copyright and patents. Here are a couple of good reads about this: 

- https://www.lexology.com/library/detail.aspx?g=5b0c0785-3eac-4cbc-ad08-2afba447b1e3
- https://tm.joomla.org/trademark-faq.html

If we want to protect the trademark Disciple.Tools, we should consider registering it, and consider using the ™ symbol (or ® once registered) for any trademarks we wish to claim.

**Comment by ChrisChasm** [comment]
You bet. We should definitely trademark Disciple.Tools. In doing that we will need to have some kind of official entity existing to register the trademark. 

In the case of Wordpress.org, they have a foundation that both protects the open source project and holds the trademark for the Wordpress logo and name.

**Comment by burntsun** [comment]
I think we should relicense DT to GPLv2 *or later*. Right now, we've only licensed it under GPLv3. There are some companies (like Apple) that have taken action against software with GPLv3, even though they accept GPLv2. Licensing this under GPLv2 or later would avoid some of these problems.

This would match WordPress's license which is GPLv2 or later: https://github.com/WordPress/WordPress/blob/master/license.txt

**Comment by ChrisChasm** [comment]
Done

**Comment by burntsun** [comment]
The LICENSE file was simply changed to contents of GPLv2 in this commit c5cf0f3b5e44d1dbad10cb5865d7093cb0a80bcc

I would like the license to be changed to GPLv2 or later. To make this clear, we need to put a paragraph at the beginning of the LICENSE file saying that the code is licensed under GPLv2 or later, the way WordPress does it: https://github.com/WordPress/WordPress/blob/master/license.txt See also the section entitled "How to Apply These Terms to Your New Programs" which is included in the GPLv2 license.

Furthermore, to make it legally binding, all the copyright holders need to agree. I think @ChrisChasm , @corsacca and me are the only copyright holders of the files (not including the files that were copied and pasted from other open source libraries). I agree to relicense all the files to which I hold copyright to in this repo, and in all other repos in this GitHub organisation at the time of writing, to GPLv2 or later.

It would also be good if all the copied and pasted code from other libraries were clearly distinct in a separate folder, or not included at all but just referenced in `composer.json` (but that's a technical change that's out of scope for this issue).

This is a useful guide: https://opensource.guide/legal/#what-if-i-want-to-change-the-license-of-my-project

**Comment by burntsun** [comment]
I've created a pull request that goes through what I think we need to do to relicense under GPLv2 or later: #223

**Comment by burntsun** [comment]
Great, @corsacca , @ChrisChasm and I agreed, the pull requests got merged, and this issue can be closed.
