### ISSUE TITLE
When posting a comment, the icon twirls (continually)

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools#208]
On the contact details page, when the user posts a comment the client doesn't get a response back from the server saying it succeed (or it does after a long wait).

This option might be the culprit:
![pasted image at 2017_10_20 11_24 am](https://user-images.githubusercontent.com/24901539/31819571-28827808-b595-11e7-8445-ea79532a343d.png)

**Comment by ChrisChasm** [comment]
@corsacca I think you are right. I spent time building our async service for the emails, so that it would not delay processing time. But if this is set, the system is probably waiting for the full api email transaction to complete before continuing. I think you are on the right tract.

**Comment by corsacca** [comment]
fixed with https://github.com/DiscipleTools/disciple-tools/commit/7b78f32559cc4e864a159b709f57331a2044d0be
