### ISSUE TITLE
Location Typeahead

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools#209]
When removing a location, that location is removed from the options when adding a new location until you refresh the page. Also, if location is simply erased, "No location set" does not appear until you refresh.

**Comment by corsacca** [comment]
The option is still available if you start typing the name. It just isn't in the "default" list.

**Comment by corsacca** [comment]
@bezcreative, is changing the text to "type to find location" sufficient?

**Comment by bezcreative** [comment]
Yep, that is sufficient.

**Comment by corsacca** [comment]
closed by a4a236c650e6c88dee358c8364f6e0f5f2b5ff2e
