### ISSUE TITLE
We need a way to know who a User is logged in as

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools#213]
--i.e. user/name in the upper right corner

**Comment by burntsun** [comment]
This was fixed by https://github.com/DiscipleTools/disciple-tools-theme/commit/16e9a4a0c8c30f5bcc5388bb9ebb68f352ce778e

I put the "fixed by" in the commit message, but I forgot that it wouldn't work because it's in a different repo.
