### ISSUE TITLE
Decide on back vs save wording on details pages in the edit fields section.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools#229]
Suggestion: Save.

**Comment by burntsun** [comment]
This was fixed by https://github.com/DiscipleTools/disciple-tools-theme/commit/b8d5c964730630b3b9153bb115b8ba4bda77ebda . Both have "Save" now. I personally think it's misleading, as changes are saved immediately, but I guess this is better than it was before.
