### ISSUE TITLE
Need icons for notification list, or remove icon placeholder

### ISSUE THREAD

**Issue by ChrisChasm** [DiscipleTools/disciple-tools#237]
We need to populate the icons for the different kind of notifications, or we need to remove the placeholder for the notifications.

@bezcreative What does your design eye tell you? Should we place icons or remove the placeholders?

**Comment by bezcreative** [comment]
@ChrisChasm I would say remove the placeholders for now. I have a lot of other stuff to work on before November. I like the idea and I think we could add them later.
