### ISSUE TITLE
Create Favicon

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools#268]

**Comment by bezcreative** [comment]
[favicomatic.zip](https://github.com/DiscipleTools/disciple-tools/files/1433652/favicomatic.zip)

Favicons for all your needs. ![bitmoji](https://render.bitstrips.com/v2/cpanel/3c97455d-0ce1-4ac8-82a0-601e6d6f6fd2-c76d709f-4308-45b4-8588-0ae0c0235db8-v1.png?transparent=1&palette=1&width=246)

**Comment by burntsun** [comment]
This is what it looks like now:

![screen shot](https://user-images.githubusercontent.com/20836899/32939481-e840f214-cb7f-11e7-8b76-23a8c98614f9.png)
