### ISSUE TITLE
Communication Channel Decision

### ISSUE THREAD

**Issue by ChrisChasm** [DiscipleTools/disciple-tools#272]
We're evaluating the best way to set up a communication strategy for on boarding developers.

After discussion, we're proposing launching a Slack channel: disciple-tools.slack.com to build the community.

**Comment by ahillbilly** [comment]
Agreed.

**Comment by burntsun** [comment]
I assume you meant "workspace" instead of "channel". Anyway, I agree with creating a Slack workspace.

**Comment by corsacca** [comment]
@ChrisChasm how do we join?

**Comment by burntsun** [comment]
@ChrisChasm You have launched a new Slack workspace. Are you ready to advertise it? If so, please post the URL here, and add a link to it in any relevant document.

**Comment by ChrisChasm** [comment]
https://disciple-tools.slack.com/signup
