### ISSUE TITLE
URL conflict for new contacts

### ISSUE THREAD

**Issue by ChrisChasm** [DiscipleTools/disciple-tools#278]
When I created a contact called "New Contact for Chris", I hijacked the link on the list page "Create new contact"

**Comment by corsacca** [comment]
There is a `//` in the url for the new contact button

**Comment by ChrisChasm** [comment]
https://github.com/DiscipleTools/disciple-tools-theme/commit/c923b7d3cdea1a7a385f9b0d163778a2ef733355
